// Simple, focused constants for current testing needs

// Environment validation
const validateEnvironment = () => {
  const requiredVars = [
    'LOGIN_USERNAME', 'LOGIN_PASSWORD', 'BASE_URL'
  ];

  const missing = requiredVars.filter(varName => !process.env[varName]);
  if (missing.length > 0) {
    console.warn(`⚠️ Missing environment variables: ${missing.join(', ')}`);
    console.warn('Please check your .env file');
  }
};

validateEnvironment();

// Timeouts
export const TIMEOUTS = {
  DEFAULT: 30000,
  LOGIN: 40000,
  PAGE_LOAD: 45000,
  ELEMENT_WAIT: 15000
};

// For backward compatibility
export const DEFAULT_TIMEOUT = TIMEOUTS.DEFAULT;

// Login Credentials
export const LOGIN_CREDENTIALS = {
  USERNAME: process.env.LOGIN_USERNAME || '',
  PASSWORD: process.env.LOGIN_PASSWORD || '',

};


// Application URLs
export const URLS = {
  LOGIN: process.env.BASE_URL || '',
};

// Screenshot paths for error handling
export const SCREENSHOT_PATHS = {
  ACCOUNTING_TAB_ERROR: 'screenshots/accounting/accounting-tab-error.png'
};

// Locator Selectors - Only what we actually use
export const SELECTORS = {

  LOGIN_USERNAME_INPUT: '//input[@id="input-login-user-name"]',
  LOGIN_PASSWORD_INPUT: '//input[@id="input-login-user-password"]',
  LOGIN_CONTINUE_BUTTON: '//input[@id="input-login-dccm-user-submit"]',
  LOGOUT_ACCOUNTICON: "//mat-icon[contains(text(),'account_circle')]",
  LOGOUT: "//span[contains(text(),'Logout')]",

//    *****Mirrior Agent Selectors *****
  DCCM: "//span[normalize-space(text()) = 'DCCM']",
  DASHBOARD_AGENTS: '//a[@title="Agents"]',
  AGENTS_MORE_ICON: "//*[normalize-space(text()) = 'more_vert']",
  AGENTS_CHECKBOX1: "(//div[contains(@class,'checkbox')])[1]",
  AGENTS_CHECKBOX2: "(//div[contains(@class,'checkbox')])[2]",
  AGENTS_CHECKBOX3: "(//div[contains(@class,'checkbox')])[3]",
  AGENTS_MIRROR_AGENT: '//button[@id="btn-role-manage-templates"]',
  AGENTS_MIRRORAGENT_VALIDATE: "(//*[contains(text(),'Mirror Agent')])[1]",
  AGENTS_MIRRORAGENT_CLOSE: '//button[contains(text(),"Close")]',
  AGENTS_MIRRORAGENT_NEXT_BUTTON: '//button[contains(text(),"Next")]',

  AGENTS_MIRRORAGENT_DIV_DROP: '//mat-select[@id="select-agentcopy-divisions"]',
  AGENTS_MIRRORAGENT_DIV_OPTION: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"All")]',
  AGENTS_MIRRORAGENT_GROUP_DROP: '//label[@for="select-agentcopy-group"]',
  AGENTS_MIRRORAGENT_GROUP_DROPDOWN_OPTION: '//mat-option[@aria-selected="true"]/preceding-sibling::mat-option[1]',
  AGENTS_MIRRORAGENT_GROUP_DROPDOWN_VAL: '(//mat-option[@aria-selected="true"]/preceding-sibling::mat-option[1])/span',
  AGENTS_MIRRORAGENT_DIV_VALUE: '(//mat-select[@id="select-agentcopy-divisions"]//following::span)[2]',
  AGENTS_MIRRORAGENT_USERNAME: "//input[@id='input-agentcopy-username']",
  AGENTS_MIRRORAGENT_SEARCH: "//span[contains(text(),'Search')]",
  AGENTS_MIRRORAGENT_ALERT_CLOSE: "//h5[contains(text(),' Alert! ')]/following::img",
  AGENTS_MIRRORAGENT_NO_USER: "(//div[contains(text(),'No users found')])[1]",
  AGENTS_DASHBOARD_SELECET_DESELECT_ALL: "//div[@title='Select/Deselect All']",
  AGENTS_MIRRORAGENT_ALERT_VALIDATE: '//div[contains(text(),"Please select atleast one agent !")]',
  AGENTS_MIRRORAGENT_ALERT_OK_BUTTON: "//button[normalize-space()='Ok']",
  AGENTS_MIRRORAGENT_USERNAME_LABEL: "(//span[contains(text(),'Mirror Agent Name')]//following::input[@type='checkbox']/following-sibling::label)[1]",
  AGENTS_MIRRORAGENT_SKILLS_LABEL: "//label[contains(text(),' Skills')]",
  AGENTS_MIRRORAGENT_QUEUES_LABEL: "//label[contains(text(),'Queues')]",
  AGENTS_MIRRORAGENT_GROUPS_LABEL: "//label[contains(text(),'Groups')]",
  AGENTS_MIRRORAGENT_LANGUAGES_LABEL: "//label[contains(text(),'Languages')]",
  AGENTS_MIRRORAGENT_PHONE_LABEL: "//label[contains(text(),'Phone')]",
  AGENTS_MIRRORAGENT_PROFILE_LABEL: "//label[contains(text(),'Profile')]",
  AGENTS_MIRRORAGENT_UTILIZATION_LABEL: "//label[contains(text(),'Utilization')]",
  AGENTS_MIRRORAGENT_ROLES_LABEL: "//label[contains(text(),'Roles')]",
  AGENTS_MIRRORAGENT_WORKTEAM_LABEL: "//label[contains(text(),'Work Team')]",
  AGENTS_MIRRORAGENT_SELECT_ATTRIBUTES_CLOSE: "//h5[contains(text(),'Select Attributes')]/following::img",
  AGENTS_MIRRORAGENT_SELECT_ATTRIBUTES_NEXT_BUTTON: "(//button[contains(text(),'Next')])[2]",
  AGENTS_MIRRORAGENT_SELECT_ATTRIBUTES_BACK_BUTTON: "//button[contains(text(),'Back')]",
  AGENTS_MIRRORAGENT_SKILL_SELECT_ALL: "//label[contains(text(),'Select All')]",
  AGENTS_MIRRORAGENT_SKILL_SEARCH_FILTER: "//input[@aria-label='Name Search Filter']",
  AGENTS_MIRRORAGENT_SKILL_LEVEL_SEARCH_FILTER: '//input[@aria-label="Level Search Filter"]',
  AGENTS_MIRRORAGENT_SKILL_NO_SKILL_AVAILABLE: "(//div[contains(text(),'There is no skill available for this selected user.')])[1]",
  AGENTS_MIRRORAGENT_SKILL_UPDATED_SUCCESSFULLY: "//*[contains(text(),' Updated successfully')]",
  AGENTS_MIRRORAGENT_SKILL_APPLY_BUTTON: "//span[contains(text(),'Apply')]",
  AGENTS_MIRRORAGENT_SKILL_SCHEDULE_BUTTON: "//span[contains(text(),'Schedule')]",
  AGENTS_MIRRORAGENT_SKILL_NUMBER_INPUT: "(//input[@type='number'])[1]",
  AGENTS_MIRRORAGENT_SKILL_NUMBER_INPUT_PARENT: "//div[contains(@class,'editable')]",
  AGENTS_MIRRORAGENT_SKILL_APPLY_CONFIRM_BUTTON: "//button[contains(text(),'Apply')]",
  AGENTS_MIRRORAGENT_SKILL_GRID_MENU: '//div[@id="copySkillGrid"]//button[@aria-label="Grid Menu"]',
  AGENTS_MIRRORAGENT_SKILL_CLEAR_ALL_FILTERS: "(//span[contains(text(),'CLEAR_ALL_FILTERS')])[2]",
  AGENTS_MIRRORAGENT_SKILL_CLEAR_ALL_SORTING: "(//span[contains(text(),'CLEAR_ALL_SORTING')])[2]",
  AGENTS_MIRRORAGENT_SKILL_TOGGLE_FILTER_ROW: "(//span[contains(text(),'TOGGLE_FILTER_ROW')])[2]",
  AGENTS_MIRRORAGENT_SKILL_EXPORT_TO_EXCEL: "(//span[contains(text(),'EXPORT_TO_EXCEL')])[2]",
  AGENTS_MIRRORAGENT_COLUMNS_SKILL_NAME: "//label[contains(text(),'Skill Name')]",
  AGENTS_MIRRORAGENT_COLUMNS_SKILL_LEVEL: "//label[contains(text(),'Skill Level')]",
  AGENTS_MIRRORAGENT_FORCE_FIT_COLUMNS: "(//label[contains(text(),'FORCE_FIT_COLUMNS')])[2]",
  AGENTS_MIRRORAGENT_SKILL_SELECT_ALL_CHECKBOX: '(//div[@title="Select/Deselect All"])[3]',
  AGENTS_MIRRORAGENT_SKILL_TAB_LANGUAGES: "//span[contains(text(),'Languages')]",
  AGENTS_MIRRORAGENT_SKILL_TAB_LANGUAGES_CHECKBOX: '(((//div[@title="Select/Deselect All"])[3])//following::input[@type="checkbox"]/parent::div)[1]',
  AGENTS_MIRRORAGENT_LANGUAGE_SEARCH_FILTER: "//input[@aria-label='Name Search Filter']",
  AGENTS_MIRRORAGENT_LANGUAGE_NO_LANGUAGE_AVAILABLE: "(//div[contains(text(),'There is no language available for this selected user.')])[1]",


  AGENTS_MIRRORAGENT_LANGUAGE_LEVEL_SEARCH_FILTER: "//input[@aria-label='Level Search Filter']",
  AGENTS_MIRRORAGENT_LANGUAGE_LEVEL_NUMBER_INPUT: '(//input[@type="number"])[1]',
  AGENTS_MIRRORAGENT_LANGUAGE_LEVEL_APPLY_BUTTON: "//span[contains(text(),'Apply')]",
  AGENTS_MIRRORAGENT_LANGUAGE_LEVEL_OVERRIDE_WARNING: "//div[contains(text(),'If you want to override skills, languages and queues, Please select override!')]",
  AGENTS_MIRRORAGENT_LANGUAGE_LEVEL_OVERRIDE_APPLY_BUTTON: "//button[contains(text(),'Apply')]",
  AGENTS_MIRRORAGENT_LANGUAGE_UPDATED_SUCCESSFULLY: "//*[contains(text(),' Updated successfully')]",
  AGENTS_MIRRORAGENT_LANGUAGE_GRID_MENU: '//div[@id="addUpdateLanguageGrid"]//button[@aria-label="Grid Menu"]',
  AGENTS_MIRRORAGENT_LANGUAGE_CLEAR_ALL_FILTERS: "(//span[contains(text(),'CLEAR_ALL_FILTERS')])[3]",
  AGENTS_MIRRORAGENT_LANGUAGE_TOGGLE_FILTER_ROW: "(//span[contains(text(),'TOGGLE_FILTER_ROW')])[3]",
  AGENTS_MIRRORAGENT_LANGUAGE_EXPORT_TO_EXCEL: "(//span[contains(text(),'EXPORT_TO_EXCEL')])[3]",
  AGENTS_MIRRORAGENT_SCHEDULE_BUTTON: '(//button[@id="btn-agentcopy-schedule"])[2]',
  AGENTS_MIRRORAGENT_SCHEDULE_JOB_TYPE_LABEL: "(//span[contains(text(),'Job Type*')])[1]",
  AGENTS_MIRRORAGENT_SCHEDULE_JOB_TYPE_ONCE: "//*[@value='once']",
  AGENTS_MIRRORAGENT_SCHEDULE_JOB_NAME: '(//input[@name="jobName"])[1]',
  AGENTS_MIRRORAGENT_SCHEDULE_START_DATE: '(//input[@name="onceDate"])[1]',
  AGENTS_MIRRORAGENT_SCHEDULE_START_DATE_CURRENT: "//button[contains(@class,'calendar-body-active')]",
  AGENTS_MIRRORAGENT_SCHEDULE_START_TIME: '(//input[@placeholder="Time at*"])[1]',
  AGENTS_MIRRORAGENT_SCHEDULE_SAVE_BUTTON: '//button[@id="once-create-btn"]',
  AGENTS_MIRRORAGENT_SKILL_TAB_QUEUES: "//span[contains(text(),'Queues') and @class='iconTitle']",
  AGENTS_MIRRORAGENT_QUEUES_SELECT_ALL_CHECKBOX: '(//div[@title="Select/Deselect All"])[3]',
  AGENTS_MIRRORAGENT_SKILL_QUEUES_CHECKBOX: '(((//div[@title="Select/Deselect All"])[3])//following::input[@type="checkbox"]/parent::div)[1]',
  AGENTS_MIRRORAGENT_QUEUES_NAME_SEARCH_TEXTBOX: '//input[@aria-label="Name Search Filter"]',
  AGENTS_MIRRORAGENT_QUEUES_ACTION_SEARCH_TEXTBOX: '//input[@aria-label="Action Search Filter"]',
  AGENTS_MIRRORAGENT_QUEUES_NO_QUEUES_AVAILABLE: "(//div[contains(text(),'There is no queue available for this selected user.')])[1]",
  AGENTS_MIRRORAGENT_QUEUES_GRID_MENU: '//div[@id="copyQueueGrid"]//button[@aria-label="Grid Menu"]',
  AGENTS_MIRRORAGENT_QUEUES_CLEAR_ALL_FILTERS: "(//span[contains(text(),'CLEAR_ALL_FILTERS')])[3]",
  AGENTS_MIRRORAGENT_QUEUES_TOGGLE_FILTER_ROW: "(//span[contains(text(),'TOGGLE_FILTER_ROW')])[3]",
  AGENTS_MIRRORAGENT_QUEUES_EXPORT_TO_EXCEL: "(//span[contains(text(),'EXPORT_TO_EXCEL')])[3]",

  DASHBOARD_REPORT: "//span[contains(text(),'Report')]",
  DASHBOARD_REPORT_SCHEDULER: "//span[contains(text(),'Scheduler')]",
  DASHBOARD_REPORT_SCHEDULER_JOB_TYPE_CURRENT: "//*[contains(text(),' Job Type - Current')]",
  DASHBOARD_REPORT_SCHEDULER_JOB_TYPE_DROPDOWN: "//label[@aria-owns='select-filter-job-type']",
  DASHBOARD_REPORT_SCHEDULER_JOB_TYPE_COMPLETED: "//span[contains(text(),'Completed ')]",
  DASHBOARD_REPORT_SCHEDULER_SEARCH_BUTTON: '//button[@id="btn-filter-search"]',
  DASHBOARD_REPORT_SCHEDULER_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
  DASHBOARD_REPORT_SCHEDULER_VALIDATE: "((//div[contains(@class,'checkbox')])[1])/following::div[2]/p",
  AGENTS_MIRRORAGENT_UTILIZATION_TAB: "//span[contains(text(),'Utilization')]",
  AGENTS_MIRRORAGENT_UTILIZATION_EXPORT_TO_EXCEL: "(//span[contains(text(),'EXPORT_TO_EXCEL')])[3]",
  AGENTS_MIRRORAGENT_GROUPS_TAB: "(//span[contains(text(),'Groups')])[3]",


  //AGENTS_MIRRORAGENT_DIV_NONE: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"None")]',
                     



  AGENTS_MIRRORAGENT_DASHBOARD_HISTORY: '//*[@id="grid"]/div[4]/div[3]/div/div[10]/div[2]',
  AGENTS_MIRRORAGENT_UTILIZATION_DESELECT:"//div[contains(@class, 'slick-header-columns')][.//span[text()='Media Type']]//div[@data-id='_checkbox_selector']//label",
  AGENTS_MIRRORAGENT_UTILIZATION_SELECT:"//div[contains(@class, 'slick-header-columns')][.//span[text()='Media Type']]//div[@data-id='_checkbox_selector']//label",
  AGENTS_MIRRORAGENT_UTILIZATION_MEDIA_SEARCH:"//div[contains(@class, 'slick-headerrow-column')]//input[@data-columnid='mediaType']",
  AGENTS_MIRRORAGENT_UTILIZATION_CAPACITY_SEARCH:"//div[contains(@class, 'slick-headerrow-column')]//input[@data-columnid='maximumCapacity']",
  AGENTS_MIRRORAGENT_UTILIZATION_GRID: "//div[contains(@class, 'slick-pane-header')][.//span[text()='Media Type']]//button[@aria-label='Grid Menu']",
  AGENTS_MIRRORAGENT_UTILIZATION_CAPACITY_INPUT:'//*[@id="copyUtilizationGrid"]/div[4]/div[3]/div/div[2]/div[3]/input',

  AGENTS_MIRRORAGENT_GROUP_DESELECT:"//div[contains(@class, 'slick-header-column')][.//span[text()='Group Name']]/preceding-sibling::div[@data-id='_checkbox_selector']//label",
  AGENTS_MIRRORAGENT_GROUP_SELECT:"//div[contains(@class, 'slick-header-column')][.//span[text()='Group Name']]/preceding-sibling::div[@data-id='_checkbox_selector']//label",
  AGENTS_MIRRORAGENT_GROUP_SEARCH:"//div[contains(@class, 'slick-headerrow-column')]//input[@data-columnid='name']",
  AGENTS_MIRRORAGENT_GROUP_GRID: "//div[@id='copyGroupGrid']//div[contains(@class, 'slick-pane slick-pane-header slick-pane-left')]//button[@aria-label='Grid Menu']",

  AGENTS_MIRRORAGENT_USERNAME_LABEL1: "(//span[contains(text(),'Mirror Agent Name')]//following::input[@type='checkbox']/following-sibling::label)[4]",
  AGENTS_MIRRORAGENT_ROLE_DESELECT:"//div[contains(@class, 'slick-header-column') and .//text()='Role']//label",
  AGENTS_MIRRORAGENT_ROLE_SELECT:"//div[contains(@class, 'slick-header-column') and .//text()='Role']//label",
  AGENTS_MIRRORAGENT_ROLE_SEARCH:'input[data-columnid="role"]',
  AGENTS_MIRRORAGENT_DIVISION_SEARCH:'//div[contains(@class, "l2") and contains(@class, "r2")]//input[@data-columnid="division"]',
  AGENT_MIRRORAGENT_ROLE_GRID:"//div[@id='copyRoleGrid']//div[contains(@class, 'slick-pane-left')]//button[@aria-label='Grid Menu']",
  AGENTS_MIRRORAGENT_CLEAR_ALL_FILTERS:"//div[contains(@class, 'slick-grid-menu') and contains(@style, 'display: block')]//li[@data-command='clear-filter']",
  AGENTS_MIRRORAGENT_TOGGLE_FILTERS:"div.slick-grid-menu[style*='display: block'] li[data-command='toggle-filter']",
  AGENTS_MIRRORAGENT_USERNAME_BULK_LABEL: "(//span[contains(text(),'Mirror Agent Name')]//following::input[@type='checkbox']/following-sibling::label)[2]",
  AGENTS_MIRRORAGENT_USERNAME_BULK_LABEL1: "(//span[contains(text(),'Mirror Agent Name')]//following::input[@type='checkbox']/following-sibling::label)[3]",
  AGENTS_MIRRORAGENT_SCHEDULER_BUTTON:'//*[@id="btn-agentcopy-schedule"]/span[1]',
  AGENTS_MIRRORAGENT_SCHEDULER_JOB_TITLE: '//*[@id="cdk-accordion-child-19"]/div/mat-dialog-content/div/div[2]/mat-form-field[1]/div[1]/div[2]',
  AGENTS_MIRRORAGENT_DIV_MEMBER: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"Member")]',
  AGENTS_MIRRORAGENT_DIV_NONE: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"None")]',
  AGENTS_MIRRORAGENT_GROUP_NONE: "(//div[contains(text(),'Please select either divisions or groups to search')])[1]",
  AGENTS_MIRRORAGENT_CONFIRM_OK: "//button[contains(text(),'Ok')]",
  AGENTS_MIRRORAGENT_SKILL_APPLY: "//*[@id='btn-agentcopy-apply']/span[1]",

//    *****SuperAdmin Selectors *****
SUPERADMIN_DASBOARD_FILTER_ICON: '//span[@id="select-filter-toggle"]',
SUPERADMIN_DASHBOARD_FILTER_ROLE: '//*[@id="select-filter-role"]',
SUPERADMIN_DASHBOARD_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
SUPERADMIN_DASHBOARD_FILTER_SEARCH: '//button[@id="btn-filter-search"]',
SUPERADMIN_DASHBOARD_FILTER_DIVISIONS: '//*[@id="select-filter-divisions"]',
SUPERADMIN_DASHBOARD_FILTER_GROUPS: '//*[@id="select-filter-groups"]',
SUPERADMIN_DASHBOARD_FILTER_TEMPLATE: '//*[@id="select-filter-template"]',
SUPERADMIN_DASHBOARD_FILTER_WORKTEAM: '//*[@id="select-filter-workteam"]',
SUPERADMIN_DASHBOARD_FILTER_QUEUE: '//*[@id="select-filter-queue"]',
SUPERADMIN_DASHBOARD_FILTER_SKILL: '//*[@id="select-filter-skill"]',
SUPERADMIN_DASHBOARD_FILTER_USERNAME: "//input[@id='input-filter-user-name']",
SUPERADMIN_DASHBOARD_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
SUPERADMIN_DASHBOARD_USER_EDIT_1: '(//i[@title="Edit"])[1]',
SUPERADMIN_DASHBOARD_USEREDIT_SCROLL_NEXT: "//button[contains(@class,'header-pagination-after')]",
SUPERADMIN_DASHBOARD_USEREDIT_CLOSE: "//h5[contains(text(),'Edit Agent - DemoUser')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_USEREDIT_QUEUES_TAB: '//div[@role="tab"]//child::span[contains(text(),"Queue")]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_QUEUE: '//*[@aria-label="Button for adding Queue"]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_QUEUE_TITLE: "//h5[contains(text(),'Add Queue')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_QUEUE_CLOSE: "//h5[contains(text(),'Add Queue')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_USEREDIT_SKILLS_TAB: "//div[@role='tab']//child::span[contains(text(),'Skills')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_SKILL_TITLE: "//h5[contains(text(),'Add Skill')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_SKILL: '//*[@aria-label="Button for adding Skill"]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_SKILL_CLOSE: "//h5[contains(text(),'Add Skill')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_USEREDIT_LANGUAGE_TAB: "//div[@role='tab']//child::span[contains(text(),'Skills')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_LANGUAGE_TITLE: "//h5[contains(text(),'Add Skill')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_LANGUAGE: '//*[@aria-label="Button for adding Skill"]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_LANGUAGE_CLOSE: "//h5[contains(text(),'Add Skill')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_USEREDIT_GROUPS_TAB: "//div[@role='tab']//child::span[contains(text(),'Groups')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_GROUPS_TITLE: "//h5[contains(text(),'Add Groups')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_GROUPS: '//*[@aria-label="Button for adding Skill"]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_GROUPS_CLOSE: "//h5[contains(text(),'Add Groups')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_USEREDIT_ROLES_DIVISION_TAB: "//div[@role='tab']//child::span[contains(text(),'Roles/Division')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_ROLES_DIVISION_TITLE: "//h5[contains(text(),' Add Role')]",
SUPERADMIN_DASHBOARD_USEREDIT_ADD_ROLES_DIVISION: '//*[@aria-label="Button for adding Data Table role"]',
SUPERADMIN_DASHBOARD_USEREDIT_ADD_ROLES_DIVISION_CLOSE: "//h5[contains(text(),'Add Role')]/following::button[contains(text(),'Close')]",
SUPERADMIN_DASHBOARD_FILTER_GROUPS_SEARCH_INPUT: '//input[@placeholder="search" and @name="groupFilterSearch"]',
SUPERADMIN_DASHBOARD_FILTER_GROUPS_SEARCH_SELECT_OPTION1: '(//*[@role="option"])[1]',
DASHBOARD_GROUPS: '//a[@title="Groups"]',
GROUPS_FILTER_MEMBER_TYPE: '//*[@id="select-filter-member-type"]',
GROUPS_FILTER_MEMBER_TYPE_GENERAL: '//*[@value="general"]',
GROUPS_FILTER_MEMBER_TYPE_SKILL: '//*[@value="skill"]',
GROUPS_FILTER_SEARCH: '//button[@id="btn-filter-search"]',
GROUPS_FILTER_ICON: '//span[@id="select-filter-toggle"]',
GROUPS_FILTER_ROLE: '//*[@id="select-filter-role"]',
GROUPS_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
GROUPS_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
GROUPS_TYPE_VALIDATE_GENERAL: "//*[contains(text(),' Type - General')]",
GROUPS_TYPE_VALIDATE_SKILL_EXPRESSION: "//*[contains(text(),' Type - Skill Expression')]",
GROUPS_ROLE_VALIDATE_SUPER_ADMIN: "//*[contains(text(),'Role - Super Administrator')]",
GROUPS_DASHBOARD_USER_EDIT_1: '(//i[@title="Edit"])[1]',
GROUPS_GENERAL_TYPE_ADD_USER: '//*[@aria-label="Button for adding Skill"]',
GROUPS_GENERAL_TYPE_EDIT_ADD_USER_VALIDATE : "//mat-label[contains(text(),'Division')]",
GROUPS_GENERAL_TYPE_EDIT_ADD_USER_CLOSE: "//h5[contains(text(),'Add Users')]/following::button[contains(text(),'Close')]",
GROUPS_GENERAL_TYPE_EDIT_GROUP_EDIT_CLOSE_BUTTON: "//h5[contains(text(),'Group Edit')]/following::span[contains(text(),'Close')]",
GROUPS_SKILLEX_TYPE_EDIT_GROUP_EDIT_DIVISIONS_TAB: "//h5[contains(text(),'Group Edit')]/following::span[contains(text(),'Divisions')]",
GROUPS_SKILLEX_TYPE_EDIT_GROUP_EDIT_ADD_USER: '//*[@aria-label="Button for adding Skill"]',
GROUPS_SKILLEX_TYPE_EDIT_ADD_USER_CLOSE: "//h5[contains(text(),'Add Division')]/following::button[contains(text(),'Close')]",
GROUPS_SKILLEX_TYPE_EDIT_GROUP_EDIT_CLOSE_BUTTON: "//h5[contains(text(),'Group Edit')]/following::span[contains(text(),'Close')]",
GROUPS_SKILLEX_TYPE_EDIT_ADD_DIVISIONS_VALIDATE: "//h5[contains(text(),'Add Divisions')]",
DASHBOARD_PHONES: '//a[@title="Phones"]',
PHONES_FILTER_ICON: '//span[@id="select-filter-toggle"]',
PHONES_FILTER_ROLE: '//*[@id="select-filter-role"]',
PHONES_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
PHONES_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
PHONES_FILTER_BASE_PHONE : '//*[@id="select-filter-base-phone"]',
PHONES_FILTER_SEARCH: '//button[@id="btn-filter-search"]',
PHONES_DASHBOARD_USER_EDIT_1: '(//i[@title="Edit"])[1]',
PHONES_FILTER_SITE_DROPDOWN : '//*[@id="select-filter-site"]',
PHONES_FILTER_PHONE_DROPDOWN_VALUES : '//div[@id="select-filter-base-phone-panel"]',
PHONES_FILTER_SITE_DROPDOWN_VALUES: '//div[@id="select-filter-site-panel"]',
PHONES_MORE_ICON: "//*[normalize-space(text()) = 'more_vert']",
PHONES_MORE_ICON_CREATE_PHONE: "//span[contains(text(),'Create Phone')]",
PHONES_CREATE_PHONE_BASE_PHONE : '//*[@id="select-createphn-base"]',
PHONES_CREATE_PHONE_SITE : '//*[@id="select-createphn-site"]',
PHONES_CREATE_PHONE_PHONENAME  : '//input[@id="input-createphn-name"]',
PHONES_CREATE_PHONE_CLOSE : '//button[@class="close_btn"]',
PHONES_CREATE_PHONE_SAVE : "//button[contains(text(),'Save')]",
PHONES_CREATE_PHONE_VALIDATE : "//h5[contains(text(),'Create Phone')]",
PHONES_CREATE_PHONE_BASE_PHONE_DROPDOWN: '//div[@id="select-createphn-base-panel"]',
PHONES_CREATE_PHONE_SITE_DROPDOWN : '//*[@id="select-createphn-site-panel"]',
DASHBOARD_DATATABLE : '//a[@title="Data Tables"]',
DATATABLE_FILTER_ICON: '//span[@id="select-filter-toggle"]',
DATATABLE_FILTER_ROLE: '//*[@id="select-filter-role"]',
DATATABLE_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
DATATABLE_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
DATATABLE_FILTER_TABLE_DROPDOWN: '//*[@id="select-filter-table"]',
DATATABLE_FILTER_TABLE_DROPDOWN_VAL : '//div[@id="select-filter-table-panel"]',
DASHBOARD_PROMPTS: '//a[@title="Prompts"]',
PROMPTS_PROMPT_NAME : '//input[@id="input-filter-prompt-name"]',
PROMPTS_FILTER_ICON: '//span[@id="select-filter-toggle"]',
PROMPTS_FILTER_ROLE: '//*[@id="select-filter-role"]',
PROMPTS_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
PROMPTS_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
DASHBOARD_OPERATING_SCHEDULES : "//span[contains(text(),'Operating Schedules')]",
DASHBOARD_SCHEDULES : '//a[@title="Schedules"]',
SCHEDULES_FILTER_ICON: '//span[@id="select-filter-toggle"]',
SCHEDULES_FILTER_ROLE: '//*[@id="select-filter-role"]',
SCHEDULES_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
SCHEDULES_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
SCHEDULES_FILTER_DIVISIONS_DROPDOWN: '//*[@id="select-filter-divisions"]',
SCHEDULES_FILTER_DIVISIONS_DROPDOWN_VAL: '//*[@id="select-filter-divisions-panel"]',
DASHBOARD_SCHEDULES_GROUPS : '//a[@title="Schedule Groups"]',
SCHEDULES_GROUPS_FILTER_SG_DROPDOWN : '//*[@id="select-filter-schedule-groups"]',
SCHEDULES_GROUPS_FILTER_SG_DROPDOWN_VAL: '//*[@id="select-filter-schedule-groups-panel"]',
SCHEDULES_GROUPS_FILTER_ICON: '//span[@id="select-filter-toggle"]',
SCHEDULES_GROUPS_FILTER_ROLE: '//*[@id="select-filter-role"]',
SCHEDULES_GROUPS_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
SCHEDULES_GROUPS_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",
SCHEDULES_GROUPS_MORE_ICON: "//*[normalize-space(text()) = 'more_vert']",
SCHEDULES_GROUPS_MORE_ICON_CREATE_SCHEDULE: '//button[@id="btn-schdlgrp-createschedules"]',
SCHEDULES_GROUPS_MORE_ICON_CREATE_SCHEDULE_DIVISION_DROPDOWN : '//*[@id="select-bulkeditphone-site"]',
SCHEDULES_GROUPS_MORE_ICON_CREATE_SCHEDULE_DIVISION_DROPDOWN_VAL: '//div[@id="select-bulkeditphone-site-panel"]',
SCHEDULES_GROUPS_MORE_ICON_CREATE_SCHEDULE_CLOSE: "//button[contains(text(),'Close')]",
DASHBOARD_DIVISIONS : '//a[@title="Divisions"]',
DIVISIONS_FILTER_ICON: '//span[@id="select-filter-toggle"]',
DIVISIONS_FILTER_ROLE: '//*[@id="select-filter-role"]',
DIVISIONS_FILTER_ROLE_SUPER_ADMIN: '//div[@id="select-filter-role-panel"]//span[contains(text(),"Super Administrator")]',
DIVISIONS_FILTER_CLOSE: "//label[contains(text(),'Filter')]/following-sibling::span",



//28-01-2026 History Audit
AGENTS_USERNAME_COPY: "(//i[contains(@title,'Edit_Agent.header')]/following::span)[1]",
AGENTS_USERNAME2_COPY: "(//i[contains(@title,'Edit_Agent.header')]/following-sibling::span)[2]",
AGENTS_USERNAME3_COPY: "(//i[contains(@title,'Edit_Agent.header')]/following-sibling::span)[3]",
AGENTS_MIRRORAGENT_HISTORY_USER: '//img[@title="History"]',
AGENTS_USERNAME_SEARCH_TEXTBOX: '//input[@aria-label="User Name Search Filter"]',
HISTORY_CURRENT_VALUE : '((//div[@class="ui-widget-content slick-row even"])[1])/div[5]',
HISTORY_CLOSE : "//button[contains(text(),'Close')]",


//29-01-2026
AGENTS_MIRRORAGENT_ALERT_SELECTGROUP: '//div[contains(text(),"Please select either divisions or groups to search")]',
AGENTS_MIRRORAGENT_GROUP_DROPDOWN_OPTION_2: '//mat-option[@aria-selected="true"]/following-sibling::mat-option[1]',
AGENTS_MIRRORAGENT_GROUP_APPLY_BUTTON: "//span[contains(text(),'Apply')]",
AGENTS_MIRRORAGENT_GROUP_OVERRIDE_WARNING: "//div[contains(text(),'If you want to override skills, languages and queues, Please select override!')]",
AGENTS_MIRRORAGENT_GROUP_OVERRIDE_APPLY_BUTTON: "//button[contains(text(),'Apply')]",
AGENTS_MIRRORAGENT_GROUP_UPDATED_SUCCESSFULLY: "//*[contains(text(),' Updated successfully')]",
AGENTS_MIRRORAGENT_GROUP_GRID_MENU: '//div[@id="addUpdateLanguageGrid"]//button[@aria-label="Grid Menu"]',
HISTORY_PROP_TAB : '(//div[@class="slick-cell l1 r1"])[1]',
AGENTS_MIRRORAGENT_PHONE_NAME: '//input[@placeholder="Phone Name"]',
AGENTS_REPORT_AUDIT : '//a[@title="Audit"]',
AGENTS_REPORT_AUDIT_PROP_TAB: '(//div[@class="slick-cell l2 r2"])[1]',
AGENTS_MIRRORAGENT_PHONE_DISABLE_CREATION: '//div[contains(@class,"switch__icons")]',

//30-01-2026
AGENTS_REPORT_AUDIT_OBJECT_NAME_TAB: '(//div[@class="slick-cell l1 r1"])[1]',
AGENTS_MIRRORAGENT_DIV_OPTION_DCCM: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"Dccm")]',
AGENTS_MIRRORAGENT_USERNAME_SEARCH_INPUT: '(//input[@data-columnid="userName"])[3]',
AGENTS_MIRRORAGENT_DIVISION_LABEL : "//label[contains(text(),'Division')]",
AGENTS_REPORT_AUDIT_PROP_NAME: '(//div[@class="slick-cell l3 r3"])[1]',
AGENTS_REPORT_AUDIT_ACTION_TYPE_ROW_1: '(//div[@class="slick-cell l6 r6"])[1]',
AGENTS_REPORT_AUDIT_ACTION_TYPE_ROW_2: '(//div[@class="slick-cell l6 r6"])[2]',
AGENT_MIRROR_AGENT_DIVISION_NAME : "//input[@name='divisionName']",
AGENTS_REPORT_AUDIT_OBJECT_NAME_MODIFIED: '(//div[@class="slick-cell l1 r1"])[2]',
AGENTS_MIRRORAGENT_USERNAME_SEARCH: "input[data-columnid='userName']",
  AGENTS_MIRRORAGENT_DIV_DCCM: '//div[@id="select-agentcopy-divisions-panel"]//span[contains(text(),"Dccm")]',
  AGENTS_MIRRORAGENT_DIV_DCCM_INPUT:'//*[@id="copyAgentGrid"]/div[4]/div[1]/div[2]/div[2]/input',
  //AGENTS_MIRRORAGENT_DIVISION_LABEL:"//label[contains(text(),'Division')]",
  AGENTS_MIRRORAGENT_WORKTEAM_APPLY_BUTTON: "//span[contains(text(),'Apply')]",
  AGENTS_MIRRORAGENT_WORKTEAM_APPLY_CONFIRM_BUTTON: "//button[contains(text(),'Apply')]",
  AGENT_WORKTEAM_VALUE : "//input[@name='workTeamName']",
  HISTORY_PROP_NAME : '//*[@id="angularGridReport"]/div[4]/div[3]/div/div[2]/div[3]',
  REPORT_SCHEDULE_VALIDATE: "//div[contains(@class, 'l2 r2')]//p[@style[contains(.,'cursor:pointer')]]",
  AGENTS_DASHBOARD_DIV_FILTER_CLICK : "//mat-chip//span[contains(@class, 'mat-mdc-chip-action-label') and contains(., 'Division - ')]",
  AGENTS_DASHBOARD_DIV_CLICK : "//mat-select[@name='divisions']",
  AGENTS_DASHBOARD_DIV_ALL_CHECKBOX : "//mat-pseudo-checkbox[contains(@class, 'mat-pseudo-checkbox-checked')]",
  AGENTS_DASHBOARD_DIV_INPUT: '//*[@id="select-filter-divisions-panel"]/mat-form-field/div[1]/div[2]',
  AGENTS_DASHBOARD_DIV_DCCM_CHECKBOX: "//mat-option[.//span[normalize-space()='Dccm']]//mat-pseudo-checkbox[not(contains(@class, 'mat-pseudo-checkbox-checked'))]",
  AGENTS_DASHBOARD_BACKDROP_CLICK :".cdk-overlay-backdrop",
  AGENTS_REPORT_JOBNAME_FILTER : "//div[contains(@class, 'l2 r2')]//input[@data-columnid='jobName']",
  REPORT_JOBNAME_VALIDATE: "//div[contains(@class, 'l2 r2')]//p[contains(@style, 'cursor:pointer')]",
  DASHBOARD_REPORT_AUDIT : "//span[contains(text(),'Audit')]",
  REPORT_AUDIT_PROPNAME: "//input[@data-columnid='propName' and contains(@class, 'filter-propName')]",


};



